goel_enterprises/app/urls.py
from django.conf import settings
from django.conf.urls.static import static


from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path,include
from django.views.generic import TemplateView

#from products.views import (
        #ProductListView,
        #product_list_view , 
        #ProductDetailView,
        #product_detail_view , 
        #ProductFeaturedDetailView ,
        #ProductFeaturedListView, 
        #ProductDetailSlugView
        #)
from accounts.views import login_page,register_page,guest_register_view
from .views import home_page,contact_page,about_page
from addresses.views import checkout_address_create_view,checkout_address_reuse_view

urlpatterns = [


    path('goel_enterprises/', home_page, name='home'),
    path('goel_enterprises/contact/',contact_page,name='contact'),
    path('goel_enterprises/register/',register_page,name='register'),
    path('goel_enterprises/bootstrap/',TemplateView.as_view(template_name="bootstrap/example.html")),
    path('goel_enterprises/login/',login_page,name='login'),
    path('goel_enterprises/logout/',LogoutView.as_view(),name='logout'),
    path('goel_enterprises/register/guest/',guest_register_view,name='guest_register'),
    path('goel_enterprises/about/',about_page,name='about'),
    path('goel_enterprises/checkout/address/create/',checkout_address_create_view,name='checkout_address_create'),
    path('goel_enterprises/checkout/address/reuse/',checkout_address_reuse_view,name='checkout_address_reuse'),
    path('goel_enterprises/cart/',include(('carts.urls','carts'), namespace='cart')),
    path('goel_enterprises/products/',include(('products.urls','products'), namespace='products')),
    path('goel_enterprises/search/',include(('search.urls','search'), namespace='search')),

    #path('products/',ProductListView.as_view()),
    #path('products-fbv/',product_list_view),
    #path('products/<int:pk>/',ProductDetailView.as_view()),
    #path("products-fbv/<int:pk>/",product_detail_view),
    #path("featured/",ProductFeaturedListView.as_view()),
    #path("featured/<int:pk>/",ProductFeaturedDetailView.as_view()),
    #path("products/<slug:slug>/",ProductDetailSlugView.as_view()),
    path('goel_enterprises/admin/', admin.site.urls),
]

#app_name = 'products'

if settings.DEBUG: 
    urlpatterns = urlpatterns + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

goel_enterprises/products/urls.py
from django.urls import path

from .views import (
        ProductListView,
        #product_list_view ,
        #ProductDetailView,
        #product_detail_view ,
        #ProductFeaturedDetailView ,
        #ProductFeaturedListView,
        ProductDetailSlugView
        )
urlpatterns = [

    path('',ProductListView.as_view(),name="list"),
    path("<slug:slug>/",ProductDetailSlugView.as_view(),name="detail"),
]

goel_enterprises/templates/base/css.html
{% load static %}

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<!--<link rel='stylesheet' href='% static "css/main.css" %}' >-->

<!-- Fontawesome CSS-->


<link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'>

goel_enterprises/templates/base/js.html
{% load static %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

goel_enterprises/templates/base/navbar.html
<!--<h1>{{ brand_name }}</h1 >-->
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as product_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}
<nav class="navbar navbar-expand-lg  navbar-dark bg-dark mb-5 navbar fixed-top">
        <div class="container">
                <a class="navbar-brand" href="{{ home_url }}">
                        <img src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
                                {% if brand_name %} {{ brand_name }} {% else %} Hello Goel Enterprises {% endif %}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                                <li class="nav-item {% if request.path == home_url %}active{% endif %}">
                                        <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
                                </li>
                               
                                <li class="nav-item  {% if request.path == product_list_url %}active{% endif %}">
                                        <a class="nav-link " href="{{ product_list_url }}" >
                                                Products
                                         </a>
                                </li>
				<li class="nav-item  {% if request.path == contact_url %}active{% endif %}">
                                        <a class="nav-link" href="{{ contact_url }}">Contact</a>
                                </li>
                                {% if request.user.is_authenticated %}
                                        <li class="nav-item {% if request.path == logout_url %}active{% endif %} ">
                                                <a class="nav-link " href="{{ logout_url }}" >
                                                        Logout
                                                </a>
                                        </li>
                                {% else %}
                                        <li class="nav-item {% if request.path == register_url %}active{% endif %} ">
                                                <a class="nav-link " href="{{ register_url }}" >
                                                        Register
                                                </a>
                                        </li>
                                        <li class="nav-item {% if request.path == login_url %}active{% endif %} ">
                                                 <a class="nav-link " href="{{ login_url }}" >
							 Login
                                                </a>
                                        </li>
                                {% endif %}
				<li class="nav-item {% if request.path == cart_url %}active{% endif %} ">
                                                 <a class="nav-link " href="{{ cart_url }}" >
							 {{ request.session.cart_items }} <!--<i class="fas fa-shopping-cart" aria-hidden="true">-->
							   Cart
							 <!--</i>-->
                                                </a>
                                        </li>
                                <!--<li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                Dropdown
                                         </a>
                                         <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                                <a class="dropdown-item" href="#">Action</a>
                                                 <a class="dropdown-item" href="#">Another action</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="dropdown-item" href="#">Something else here</a>
                                </div>
				</li>-->
                </ul>
     			{% include 'search/snippets/search-form.html' %}         
		</div>
	</div>
</nav>